//
// Created by Cosmin on 05-Nov-19.
//

#ifndef FOOD_ORDERING_CONSTANTS_H
#define FOOD_ORDERING_CONSTANTS_H

#define MAX_FOOD_TYPE_NAME 10
#define FOOD_OPTIONS 4
#define MAX_FOOD_OPTION_NAME 50
#define MAX_DRINK_NAME 10

#endif //FOOD_ORDERING_CONSTANTS_H
